### PR TITLE
chore: Keep public directory empty

### PR DESCRIPTION
**Pull request by danfarrow**

### CODE REVIEW

**Comment by danfarrow** [comment]
Just wondering how this will affect the publicly available report in the `report` branch?

**Comment by ryelle** [comment]
The gitignore will apply there too, so it won't commit the report. I think you can delete these files without adding the gitignore, though then people might accidentally add them in PRs. 

Or we could keep the gitignore, and change the report action to force-add `public_html`, if possible.

**Comment by danfarrow** [comment]
Maybe I’ll remove the gitignore for now and we can see how it goes

**Review by ryelle — APPROVED** [review]

**Comment by danfarrow** [comment]
After merging this PR the [`Merge trunk -> report` action has a merge conflict](https://github.com/WordPress/css-audit/runs/2821332459?check_suite_focus=true). It seems to be because `wp-admin.html` has been modified in the `report` branch which I verified by trying the merge locally.

So... I’m not sure what the right solution is here. If I update `.gitignore` in `trunk` to ignore the contents of `/public` then that will get merged into the `report` automatically. 

Could the action selectively merge everything _except_ `.gitignore`? Or could the Action somehow resolve the merge conflict each time? Or maybe the report could be generated in `trunk` and then merged into `report` to they both contain the latest version?

**Comment by ryelle** [comment]
I believe the commit action has an option to force the commit, which would override the conflict and force report to be synced with trunk. That sounds like the behavior we want, what do you think?

**Comment by danfarrow** [comment]
I’m looking into this. [It seems you can “pre-specify” a conflict resolution for specific files](https://gist.github.com/tmaybe/4c9d94712711229cd506) using `.gitattributes`. I’ll try it locally

**Pull request merged**
