### PR TITLE
Feature/styling

### PR DESCRIPTION
**Pull request by danfarrow**
hi @ryelle, I've now merged everything, fixed a couple of little CSS issues & deleted the redundant templates. 

I also regenerated the report. The PR process is starting to make more sense to me but please let me know if there's anything I haven't done right.

Thanks again!

p.s. sorry you had to fix all my non-WP-standards-compliant indentation :facepalm:

### CODE REVIEW

**Comment by ryelle** [comment]
@danfarrow I updated and merged #15 yesterday after I caused you a bunch of merge conflicts by merging #12, sorry you ended up doing it all again! I see you've fixed a few things in the styles though, so I'll merge this too 👍

**Comment by danfarrow** [comment]
@ryelle oh no the merging wasn't too bad, I did get your updates from yesterday which fixed nearly everything. It may be that I somehow included your updates in this PR because I wasn't sure how I should be updating my local repo. Thinking about it now I probably should have deleted my previous branch and set up another one :roll_eyes:

**Comment by danfarrow** [comment]
@ryelle I've now switched my local repo to `master`, merged in the `feature/styling` branch, then ran `git pull upstream master`. Does that sound about right?

**Comment by danfarrow** [comment]
oh I should also push my local repo to my fork / `origin`

**Comment by ryelle** [comment]
> switched my local repo to `master`, merged in the `feature/styling` branch, then ran `git pull upstream master`.

Almost right— you don't need to have merged `feature/styling` since I already did through GitHub. Just pulling down master `git pull upstream master` should update things correctly. I usually delete the local branch once a PR is merged, that way you can check out a new branch off the current `master` branch, and it should avoid all that extra merge history.

If you find you're having trouble with merges, or you have local changes in origin/master that aren't in upstream/master, you can force reset everything using this (note, it will blow away any local work that isn't in a branch):

```
git checkout master
git fetch upstream
git reset --hard upstream/master
```

**Comment by danfarrow** [comment]
Thank you, that's very helpful. Good to know `git reset --hard` is there as a last resort!

**Pull request merged**
