### PR TITLE
Switch default parser to PostCSS

### PR DESCRIPTION
**Pull request by ryelle**
Replace the parser for each audit with `PostCSS`, which will let us use postcss plugins (like the values parser) to more accurately walk through rules and properties.

The only exception is the media queries rule, because (at least for now), I can't replicate the same parsing there, so that will stay using `csstree`. I added some notes [explaining the reasoning to the readme](https://github.com/ryelle/css-audit/tree/update/switch-parser-postcss#technical-details).

This change fixes two miscounts:
- Colors in non-color values (like image urls) were being counted as colors in use
- Nested selectors in `:not(…)` were being counted as separate selectors, inflating the "total selector count"

### CODE REVIEW

**Comment by laras126** [comment]
@ryelle What's left to do on this one? Can I help? I had an idea for a new audit and can use PostCSS from the get go after this is merged (also I am already familiar with it!).

**Comment by ryelle** [comment]
The remaining tasks were mostly administrative - I had to actually write the description :)

If you want to test this out to make sure nothing unexpected has changed, that would help.

**Comment by danfarrow** [comment]
hi Kelly, I just checked this pr out, ran the tests & generated a report. I didn't experience any issues, looks good!

**Comment by danfarrow** [comment]
Oh hold on, I seem to have spoken too soon! I realised that I should’ve deleted the existing report, so I did that and tried to regenerate it and it's failing. Looking into it now...

**Comment by danfarrow** [comment]
ok my fault! I was inadvertently including .scss files in my `npm run css-audit`

I changed the file selector to `**/*.css` and it's all good :+1:

**Pull request merged**
