### PR TITLE
Bugfix/missing darkmode for single audit report

### PR DESCRIPTION
**Pull request by danfarrow**
I noticed that in the HTML report, because the nav was only generated for reports with more than one audit, the dark-mode switch was not added to the HTML when generating a report with a single audit. 

Just needed to move the twig `{% if reports|length > 1 %}...{% endif %}` condition

### CODE REVIEW

**Comment by danfarrow** [comment]
oh whoops I think I should've rebased before creating the PR?

**Comment by ryelle** [comment]
@danfarrow yeah, if you could rebase that would help fix the conflicts. let me know if you run into issues, I can try to cherry-pick out the fix.

**Comment by danfarrow** [comment]
@ryelle I'll give it a go!

**Comment by danfarrow** [comment]
I think I'll close this & try again...

**Pull request closed without merging**
